### ISSUE TITLE
Color of BoxVertexColors.gltf is not displayed

### ISSUE THREAD

**Issue by cx20** [pissang/clay-viewer#14]
I tried to display BoxVertexColors.gltf.
https://github.com/cx20/gltf-test/tree/master/sampleModels/BoxVertexColors
![image](https://user-images.githubusercontent.com/1833979/33805203-408138a0-ddf8-11e7-9cff-d38fee4c8029.png)
However, the color was not displayed in the box.
https://cx20.github.io/gltf-test/examples/qtek/index.html?model=BoxVertexColors&scale=1
![image](https://user-images.githubusercontent.com/1833979/33805213-6552be60-ddf8-11e7-89e6-b4d80fa09345.png)
Is vertex color still not supported?

**Comment by pissang** [comment]
Vertex color is not supported yet. Will add it later:)

**Comment by cx20** [comment]
I tried the following newly added new sample.

https://cx20.github.io/gltf-test/examples/qtek/index.html?category=tutorialModels&model=VertexColorTest&scale=1.0&type=glTF
![image](https://user-images.githubusercontent.com/1833979/34914559-3bb4cdf2-f958-11e7-9986-094e2924d563.png)

The correct result is as follows.
https://github.com/emackey/glTF-Sample-Models/tree/vertex-color-test/2.0/VertexColorTest
![image](https://user-images.githubusercontent.com/1833979/34914570-7ec27dec-f958-11e7-9819-525a44a271b9.png)

**Comment by pissang** [comment]
Hi @cx20 , GLTF loader in ClayGL(original qtek) has supported vertex colors now:)

**Comment by cx20** [comment]
I confirmed that [BoxVertexColors.gltf](https://cx20.github.io/gltf-test/examples/claygl/index.html?model=BoxVertexColors&scale=1) and [VertexColorTest.gltf](https://cx20.github.io/gltf-test/examples/claygl/index.html?category=tutorialModels&model=VertexColorTest&scale=1.0&type=glTF) can be displayed in ClayGL.

And I changed the name of the library in the list of gltf-test from QMV.js to ClayGL.
https://github.com/cx20/gltf-test

**Comment by pissang** [comment]
BTW, It's really nice to see you already used latest API of ClayGL in the https://github.com/cx20/gltf-test.  Just want to comment to you about the change of ClayGL version 1.0.0 :)

**Comment by cx20** [comment]
https://github.com/pissang/claygl/issues/43
