### ISSUE TITLE
emty window

### ISSUE THREAD

**Issue by NickolayTeplykh** [pissang/clay-viewer#18]
Buttons "save" "load" open an empty window without the possibility of its functioning
![default](https://user-images.githubusercontent.com/36074146/35763931-660c3874-08e9-11e8-87ec-b2af2cb565e0.jpg)

**Comment by djalexv** [comment]
This error only appears in the standalone Windows application . In the browser version
https://pissang.github.io/clay-viewer/editor/ there is no such error.

![000](https://user-images.githubusercontent.com/36099172/35766906-73b9cf8e-0913-11e8-9e27-c4f0788ede85.jpg)

**Comment by pissang** [comment]
Removed useless save/load button in the latest release.
