### ISSUE TITLE
Numpad

### ISSUE THREAD

**Issue by yanghe1** [pissang/clay-viewer#19]
Hello!
The program does not work properly with numpad. I can only add the highest digit to a number but the program does not respond to other actions.

**Comment by djalexv** [comment]
I confirm. There is no possibility to directly enter a fractional number into the digital field. Changing the digital fields is possible with an accuracy of 0.1 using the up and down arrows. This seems to be a feature.
In addition, with these fields it is not possible to perform copy-paste operations.

**Comment by pissang** [comment]
Yeah it's really annoying. The numpad is a component of [ControlKit](https://github.com/pissang/controlkit.js) Will fix it later.

**Comment by pissang** [comment]
Number input UI has been improved in the 0.2.1 release https://github.com/pissang/clay-viewer/releases/tag/0.2.1
