### ISSUE TITLE
Rotate of the model

### ISSUE THREAD

**Issue by yanghe1** [pissang/clay-viewer#20]
I noticed strange reaction of the workplace to my action.

Steps to reproduce:
1. Clamp the left button at the workplace;
2. Drag the cursor out of the program field with clamped button;
3. Unclamp left button and try to rotate the model. You can do it.

Is it a bug or a feature?

![11112](https://user-images.githubusercontent.com/36100022/35766145-e208b02c-0904-11e8-8f30-d0ec7398e10a.gif)

**Comment by pissang** [comment]
Confirmed it's a bug
