### ISSUE TITLE
Digital filed 

### ISSUE THREAD

**Issue by djalexv** [pissang/clay-viewer#22]
In addition to problems with NUMPAD https://github.com/pissang/clay-viewer/issues/19,  all digital fields do not allow performing copy / paste operations.  
And also in materials, when you try to change the value in the digital fields with the up and down arrows, the change occurs only by an integer. At the same time, the slider can be changed to fractional values.

**Comment by pissang** [comment]
Thanks for the supplement @djalexv . I will have a look at it.

**Comment by pissang** [comment]
Number input UI has been improved in the 0.2.1 release https://github.com/pissang/clay-viewer/releases/tag/0.2.1
