### ISSUE TITLE
Incorrect behavior of number inputs

### ISSUE THREAD

**Issue by wbolh** [pissang/clay-viewer#26]
It is related to controlkit and its weird validation of such fields. If you place caret left from decimal point and press Delete key, the number in the field will be multiplied by 100. It works with all fields.
Eg: 0.50 -> 50.00, 1.23 -> 123.00 etc.

**Comment by pissang** [comment]
Same issue with https://github.com/pissang/clay-viewer/issues/19 and https://github.com/pissang/clay-viewer/issues/22

**Comment by pissang** [comment]
Number input UI has been improved in the 0.2.1 release https://github.com/pissang/clay-viewer/releases/tag/0.2.1
