### ISSUE TITLE
Right click of the mouse repeats previous press mouse button (left click or middle click)

### ISSUE THREAD

**Issue by Shattesther** [pissang/clay-viewer#34]
Right click of the mouse repeats previous press mouse button (left click or middle click). 
If you rotate the scene clicking by the left button then the right button will rotate too. If you move the scene clicking by the middle button then the right button will move the scene too.
Is it correct behavior (feature) or bug?
![33333](https://user-images.githubusercontent.com/12807377/35794346-fa7f1810-0a87-11e8-8a93-e8ac9cd71242.gif)

**Comment by pissang** [comment]
It's not a expected behavior. Disabled the right button in the latest commit. It will be fixed in the next release. Thanks for the report!
