### ISSUE TITLE
Mouse interaction with model view

### ISSUE THREAD

**Issue by Alyon-ka** [pissang/clay-viewer#37]
**Environment:**
CPU: I5-3337U, RAM: 6Gb, GPU: NVIDIA 710M
Windows 10 x64, build 1607. 
**Build**
qtek-model-viewer-0.1.1-win
**Description:**
Hello.
When you are change model view by pressed any mouse button and then move mouse cursor outside program window and release button, program saves mouse button state. And when you return back mouse cursor to program window you get model view changing without mouse pressed button.

**Comment by pissang** [comment]
Thanks for the report! It's a known issue. See https://github.com/pissang/clay-viewer/issues/20
