### ISSUE TITLE
Clicking "load" and "save" buttons opens an empty windows

### ISSUE THREAD

**Issue by CheatB** [pissang/clay-viewer#54]
Environment: Win 10.
When I click "load" and "save" buttons it opens an empty windows, is it bug?
![image](https://user-images.githubusercontent.com/30426916/36582692-ffcf6e8e-18a4-11e8-8f4c-3d2f8ea3e2b3.png)

**Comment by pissang** [comment]
Similar to https://github.com/pissang/clay-viewer/issues/52 . Will remove these two unused buttons
