### ISSUE TITLE
"Ground" — Z=0 dissapear issue [Win/Web] [0.1.1]

### ISSUE THREAD

**Issue by SibDiP** [pissang/clay-viewer#62]
##  **Test stand** : 
OS: Windows 10 64-bit CPU Intel Core i3 4160 @ 3.60GHz Haswell 22nm Technology       
RAM: 8,00ГБ Dual-Channel DDR3   (9-9-9-24)       
Motherboard: Gigabyte Technology Co. Ltd.   H81M-S1 (SOCKET 0)       
Graphics: SyncMaster (1680x1050@60Hz)        Intel HD Graphics 4400   (Gigabyte)       
Storage: 119GB Samsung SSD 850 PRO 128GB   (SSD), 5581GB Microsoft Storage Space Device       

## **Programm Info:**
Version: 0.1.1
Platform: desktop (Win/Web)

## **Descripton:**
When "Ground" checkbox on — Part of [3D model](https://sketchfab.com/models/2179505e74fe46dfa3f38d7ef6a9a40b) with z=0 disappear when camera look from behind. When "Ground" checkbox off — no such problem.

## **Steps:**
1. Open qtek-model-viewer.exe 
2. Import [3D model](https://sketchfab.com/models/2179505e74fe46dfa3f38d7ef6a9a40b) 
3. Mooving camera around the model  ![giphy 1](https://user-images.githubusercontent.com/13715548/36640574-32ef18f4-1a54-11e8-91d0-6e873d2ffba3.gif)
4. Turn off "Ground" checkbox.
5. Mooving camera around the model | Сorrectly displayed

**Comment by pissang** [comment]
Hi @SibDiP It has been fixed in the latest release. https://github.com/pissang/clay-viewer/releases/tag/0.2.1
