### ISSUE TITLE
Incorrect visualization of selected element contour

### ISSUE THREAD

**Issue by CheatB** [pissang/clay-viewer#66]
Environment
OS: Windows 10 64-bit

Program info:
Version: 0.1.1 desktop (Win)

Description:
Contour of selected element is displayed incorrectly while changing point of view on the model. This bug checked only in desktop version of program, web version doesn't have such problems.

Steps:
1. Open qtek-model-viewer.exe
2. Import any 3D model
3. Select any element of model
4. Change point of view  on model

![image](https://user-images.githubusercontent.com/30426916/36642188-55628a82-1a6e-11e8-9160-f48b04e4adf4.png)

**Comment by pissang** [comment]
Same with https://github.com/pissang/clay-viewer/issues/71
