### ISSUE TITLE
[Bug] Sticking camera rotation while release the button [Win][0.1.1]

### ISSUE THREAD

**Issue by bspotf** [pissang/clay-viewer#69]
Environment:
Notebook Dell Inspiron N5110
Intel Core i5-2430M CPU 2.4GHz 6Gb RAM Intel HD Graphics 3000 GPU
OS: Windows 10 Home 64-bit

Program info:
Version: 0.1.1 desktop (Win)

Problem:
Sometimes while clicking left button to rotate the camera it "sticks" and continue camera rotation if you release the button

Steps:
1. Open qtek-model-viewer.exe
2. Import any 3D model
3. Try to rotate the camera by clicking left button

**Comment by pissang** [comment]
Same with https://github.com/pissang/clay-viewer/issues/20 .
