### ISSUE TITLE
[Bug] Incorrect display of some highlighted details [Win][0.1.1]

### ISSUE THREAD

**Issue by bspotf** [pissang/clay-viewer#71]
Environment:
Notebook Dell Inspiron N5110
Intel Core i5-2430M CPU 2.4GHz 6Gb RAM Intel HD Graphics 3000 GPU
OS: Windows 10 Home 64-bit

Program info:
Version: 0.1.1 desktop (Win)

Problem:
Some parts of 3d model are not highlighted correctly (see gif)
![highlightingbug_gif](https://user-images.githubusercontent.com/33741582/36676282-d408fa22-1b3d-11e8-9f77-b8148081f1d2.gif)

Steps:
1. Open qtek-model-viewer.exe
2. Import any 3D model
3. Select any part of the model
4. Scale the incorrectly highlighted

**Comment by pissang** [comment]
Hi @bspotf . Can you mailing me the model for testing

**Comment by bspotf** [comment]
Hello. Forgot to attach, sorry for that. 
You can find it at link: https://sketchfab.com/features/gltf
[steampunkExplorer.zip](https://github.com/pissang/clay-viewer/files/1770281/steampunkExplorer.zip)
