### ISSUE TITLE
ssao的BlurShader中疑似bug

### ISSUE THREAD

**Issue by shawn0326** [pissang/clay-viewer#93]
ssao.glsl 中：
`w *= (1.0 - smoothstep(abs(centerDepth - d) / depthRange, 0.0, 1.0));`
是否是
`w *= (1.0 - smoothstep(0.0, 1.0, abs(centerDepth - d) / depthRange));`
的误写，感觉下一种写法更容易理解？

另外，上一种写法，在chrome 的 --headless 模式下，会导致部分渲染错误。

**Comment by pissang** [comment]
@shawn0326 是的这里写错了，谢谢提醒:)
